version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://app:3000
      SOCKET_SERVER: http://socket:4000
    depends_on:
      - socket
      - mongo
      - redis

  socket:
    build:
      context: ../socket
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
